import { Response } from 'express';
import { AuthRequest } from '../middleware/auth';
import { askGroq, extractJson } from '../utils/groq';
import { Planner } from '../models/Planner';

export const generatePlanner = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { subjects, examDate, hoursPerDay, durationDays, weakTopics } = req.body;

    if (!subjects || !hoursPerDay || !durationDays) {
      res.status(400).json({ message: 'Subjects, hoursPerDay, and durationDays are required' });
      return;
    }

    const prompt = `Create a structured study plan based on the following inputs:
- Subjects: ${subjects.join(', ')}
- Duration: ${durationDays} days
- Daily Study Hours: ${hoursPerDay} hours
- Exam Date: ${examDate || 'Not specified'}
- Weak Topics: ${weakTopics && weakTopics.length > 0 ? weakTopics.join(', ') : 'None specified'}

Output ONLY a strictly valid JSON object representing the study plan. NO markdown formatting, NO backticks, NO code blocks.
The JSON must have the following structure exactly:
{
  "schedule": [
    {
      "day": "Day 1 (e.g. Monday or date)",
      "tasks": [
        { "time": "2 hrs", "activity": "Study Operating Systems" },
        ...
      ]
    },
    ...
  ],
  "priorities": ["Priority 1", "Priority 2", ...],
  "revisionPlan": "A short summary of the revision strategy."
}`;

    const aiResponse = await askGroq(prompt);
    const cleanResponse = extractJson(aiResponse);
    const parsedPlan = JSON.parse(cleanResponse);

    // --- Dynamic AI JSON Structure Normalization (Bulletproof Parser) ---
    
    // 1. Extract Schedule Array
    let scheduleArray: any[] = [];
    if (parsedPlan && Array.isArray(parsedPlan.schedule)) {
      scheduleArray = parsedPlan.schedule;
    } else if (parsedPlan && parsedPlan.plan && Array.isArray(parsedPlan.plan.schedule)) {
      scheduleArray = parsedPlan.plan.schedule;
    } else if (parsedPlan && parsedPlan.studyPlan && Array.isArray(parsedPlan.studyPlan.schedule)) {
      scheduleArray = parsedPlan.studyPlan.schedule;
    } else if (Array.isArray(parsedPlan)) {
      scheduleArray = parsedPlan;
    } else if (parsedPlan && typeof parsedPlan === 'object') {
      // Look through object fields for any array field
      for (const key in parsedPlan) {
        if (Array.isArray(parsedPlan[key])) {
          scheduleArray = parsedPlan[key];
          break;
        }
      }
    }

    // Normalize schedule fields to match IPlanner schema: { day: string, tasks: { time: string, activity: string }[] }
    const normalizedSchedule = scheduleArray.map((dayItem: any, index: number) => {
      let dayName = 'Day ' + (index + 1);
      if (dayItem && typeof dayItem.day === 'string') {
        dayName = dayItem.day;
      } else if (dayItem && dayItem.day !== undefined) {
        dayName = `Day ${dayItem.day}`;
      }

      let rawTasks = (dayItem && (dayItem.tasks || dayItem.activities)) || [];
      if (!Array.isArray(rawTasks)) {
        rawTasks = [];
      }

      const normalizedTasks = rawTasks.map((t: any) => {
        if (!t) return { time: 'Duration unspecified', activity: 'Study session' };
        if (typeof t === 'string') {
          return { time: 'Duration unspecified', activity: t };
        }
        return {
          time: typeof t.time === 'string' ? t.time : 'Duration unspecified',
          activity: typeof t.activity === 'string' ? t.activity : (t.task || t.description || 'Study session')
        };
      });

      return {
        day: dayName,
        tasks: normalizedTasks
      };
    });

    // 2. Extract Revision Plan String
    let revisionPlanStr = 'Revision schedule generated by Groq AI.';
    if (parsedPlan) {
      if (typeof parsedPlan.revisionPlan === 'string') {
        revisionPlanStr = parsedPlan.revisionPlan;
      } else if (parsedPlan.plan && typeof parsedPlan.plan.revisionPlan === 'string') {
        revisionPlanStr = parsedPlan.plan.revisionPlan;
      } else if (parsedPlan.studyPlan && typeof parsedPlan.studyPlan.revisionPlan === 'string') {
        revisionPlanStr = parsedPlan.studyPlan.revisionPlan;
      } else if (typeof parsedPlan.strategy === 'string') {
        revisionPlanStr = parsedPlan.strategy;
      } else if (typeof parsedPlan.summary === 'string') {
        revisionPlanStr = parsedPlan.summary;
      }
    }

    // 3. Extract Priorities Array
    let prioritiesArray: string[] = [];
    if (parsedPlan) {
      if (Array.isArray(parsedPlan.priorities)) {
        prioritiesArray = parsedPlan.priorities;
      } else if (parsedPlan.plan && Array.isArray(parsedPlan.plan.priorities)) {
        prioritiesArray = parsedPlan.plan.priorities;
      } else if (parsedPlan.studyPlan && Array.isArray(parsedPlan.studyPlan.priorities)) {
        prioritiesArray = parsedPlan.studyPlan.priorities;
      }
    }

    // Save generated planner to DB with verified and normalized shape
    const savedPlanner = await Planner.create({
      userId: req.user._id,
      subjects,
      examDate: examDate ? new Date(examDate) : new Date(Date.now() + durationDays * 24 * 60 * 60 * 1000),
      hoursPerDay: parseInt(hoursPerDay),
      durationDays: parseInt(durationDays),
      weakTopics: weakTopics || [],
      schedule: normalizedSchedule,
      priorities: prioritiesArray,
      revisionPlan: revisionPlanStr,
    });

    res.status(201).json(savedPlanner);
  } catch (error) {
    console.error('Planner generation error:', error);
    res.status(500).json({ message: 'Server Error generating planner' });
  }
};

export const getLatestPlanner = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const allPlanners = await Planner.find({ userId: req.user._id }).sort({ createdAt: -1 });
    res.json(allPlanners);
  } catch (error) {
    console.error('Failed to get all planners:', error);
    res.status(500).json({ message: 'Server Error fetching planners' });
  }
};

export const markPlannerAsDone = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const planner = await Planner.findOneAndUpdate(
      { _id: id, userId: req.user._id },
      { isCompleted: true },
      { new: true }
    );
    if (!planner) {
      res.status(404).json({ message: 'Planner not found' });
      return;
    }
    res.status(200).json({ message: 'Planner marked as completed successfully', planner });
  } catch (error) {
    console.error('Failed to mark planner as done:', error);
    res.status(500).json({ message: 'Server Error marking planner as done' });
  }
};
